{-# LANGUAGE OverloadedStrings #-}

-- | Error and reply codes defined by http://www.ietf.org/rfc/rfc1459.txt
module IRC.Codes where

import Data.ByteString

err_UNKNOWNERROR :: ByteString
err_UNKNOWNERROR = "400"
err_NOSUCHNICK :: ByteString
err_NOSUCHNICK = "401"
err_NOSUCHSERVER :: ByteString
err_NOSUCHSERVER = "402"
err_NOSUCHCHANNEL :: ByteString
err_NOSUCHCHANNEL = "403"
err_CANNOTSENDTOCHAN :: ByteString
err_CANNOTSENDTOCHAN = "404"
err_TOOMANYCHANNELS :: ByteString
err_TOOMANYCHANNELS = "405"
err_WASNOSUCHNICK :: ByteString
err_WASNOSUCHNICK = "406"
err_TOOMANYTARGETS :: ByteString
err_TOOMANYTARGETS = "407"
err_NOORIGIN :: ByteString
err_NOORIGIN = "409"
err_NORECIPIENT :: ByteString
err_NORECIPIENT = "411"
err_NOTEXTTOSEND :: ByteString
err_NOTEXTTOSEND = "412"
err_NOTOPLEVEL :: ByteString
err_NOTOPLEVEL = "413"
err_WILDTOPLEVEL :: ByteString
err_WILDTOPLEVEL = "414"
err_UNKNOWNCOMMAND :: ByteString
err_UNKNOWNCOMMAND = "421"
err_NOMOTD :: ByteString
err_NOMOTD = "422"
err_NOADMININFO :: ByteString
err_NOADMININFO = "423"
err_FILEERROR :: ByteString
err_FILEERROR = "424"
err_NONICKNAMEGIVEN :: ByteString
err_NONICKNAMEGIVEN = "431"
err_ERRONEUSNICKNAME :: ByteString
err_ERRONEUSNICKNAME = "432"
err_NICKNAMEINUSE :: ByteString
err_NICKNAMEINUSE = "433"
err_NICKCOLLISION :: ByteString
err_NICKCOLLISION = "436"
err_USERNOTINCHANNEL :: ByteString
err_USERNOTINCHANNEL = "441"
err_NOTONCHANNEL :: ByteString
err_NOTONCHANNEL = "442"
err_USERONCHANNEL :: ByteString
err_USERONCHANNEL = "443"
err_NOLOGIN :: ByteString
err_NOLOGIN = "444"
err_SUMMONDISABLED :: ByteString
err_SUMMONDISABLED = "445"
err_USERSDISABLED :: ByteString
err_USERSDISABLED = "446"
err_NOTREGISTERED :: ByteString
err_NOTREGISTERED = "451"
err_NEEDMOREPARAMS :: ByteString
err_NEEDMOREPARAMS = "461"
err_ALREADYREGISTRED :: ByteString
err_ALREADYREGISTRED = "462"
err_NOPERMFORHOST :: ByteString
err_NOPERMFORHOST = "463"
err_PASSWDMISMATCH :: ByteString
err_PASSWDMISMATCH = "464"
err_YOUREBANNEDCREEP :: ByteString
err_YOUREBANNEDCREEP = "465"
err_KEYSET :: ByteString
err_KEYSET = "467"
err_CHANNELISFULL :: ByteString
err_CHANNELISFULL = "471"
err_UNKNOWNMODE :: ByteString
err_UNKNOWNMODE = "472"
err_INVITEONLYCHAN :: ByteString
err_INVITEONLYCHAN = "473"
err_BANNEDFROMCHAN :: ByteString
err_BANNEDFROMCHAN = "474"
err_BADCHANNELKEY :: ByteString
err_BADCHANNELKEY = "475"
err_NOPRIVILEGES :: ByteString
err_NOPRIVILEGES = "481"
err_CHANOPRIVSNEEDED :: ByteString
err_CHANOPRIVSNEEDED = "482"
err_CANTKILLSERVER :: ByteString
err_CANTKILLSERVER = "483"
err_NOOPERHOST :: ByteString
err_NOOPERHOST = "491"
err_UMODEUNKNOWNFLAG :: ByteString
err_UMODEUNKNOWNFLAG = "501"
err_USERSDONTMATCH :: ByteString
err_USERSDONTMATCH = "502"

rpl_WELCOME :: ByteString
rpl_WELCOME = "001"
rpl_YOURHOST :: ByteString
rpl_YOURHOST = "002"
rpl_CREATED :: ByteString
rpl_CREATED = "003"
rpl_MYINFO :: ByteString
rpl_MYINFO = "004"
rpl_BOUNCE :: ByteString
rpl_BOUNCE = "005"
rpl_ISSUPPORTED :: ByteString
rpl_ISSUPPORTED = "005"

rpl_NONE :: ByteString
rpl_NONE = "300"
rpl_USERHOST :: ByteString
rpl_USERHOST = "302"
rpl_ISON :: ByteString
rpl_ISON = "303"
rpl_AWAY :: ByteString
rpl_AWAY = "301"
rpl_UNAWAY :: ByteString
rpl_UNAWAY = "305"
rpl_NOWAWAY :: ByteString
rpl_NOWAWAY = "306"
rpl_WHOISUSER :: ByteString
rpl_WHOISUSER = "311"
rpl_WHOISSERVER :: ByteString
rpl_WHOISSERVER = "312"
rpl_WHOISOPERATOR :: ByteString
rpl_WHOISOPERATOR = "313"
rpl_WHOISIDLE :: ByteString
rpl_WHOISIDLE = "317"
rpl_ENDOFWHOIS :: ByteString
rpl_ENDOFWHOIS = "318"
rpl_WHOISCHANNELS :: ByteString
rpl_WHOISCHANNELS = "319"
rpl_WHOWASUSER :: ByteString
rpl_WHOWASUSER = "314"
rpl_ENDOFWHOWAS :: ByteString
rpl_ENDOFWHOWAS = "369"
rpl_LISTSTART :: ByteString
rpl_LISTSTART = "321"
rpl_LIST :: ByteString
rpl_LIST = "322"
rpl_LISTEND :: ByteString
rpl_LISTEND = "323"
rpl_CHANNELMODEIS :: ByteString
rpl_CHANNELMODEIS = "324"
rpl_NOTOPIC :: ByteString
rpl_NOTOPIC = "331"
rpl_TOPIC :: ByteString
rpl_TOPIC = "332"
rpl_INVITING :: ByteString
rpl_INVITING = "341"
rpl_SUMMONING :: ByteString
rpl_SUMMONING = "342"
rpl_VERSION :: ByteString
rpl_VERSION = "351"
rpl_WHOREPLY :: ByteString
rpl_WHOREPLY = "352"
rpl_ENDOFWHO :: ByteString
rpl_ENDOFWHO = "315"
rpl_NAMREPLY :: ByteString
rpl_NAMREPLY = "353"
rpl_ENDOFNAMES :: ByteString
rpl_ENDOFNAMES = "366"
rpl_LINKS :: ByteString
rpl_LINKS = "364"
rpl_ENDOFLINKS :: ByteString
rpl_ENDOFLINKS = "365"
rpl_BANLIST :: ByteString
rpl_BANLIST = "367"
rpl_ENDOFBANLIST :: ByteString
rpl_ENDOFBANLIST = "368"
rpl_INFO :: ByteString
rpl_INFO = "371"
rpl_ENDOFINFO :: ByteString
rpl_ENDOFINFO = "374"
rpl_MOTDSTART :: ByteString
rpl_MOTDSTART = "375"
rpl_MOTD :: ByteString
rpl_MOTD = "372"
rpl_ENDOFMOTD :: ByteString
rpl_ENDOFMOTD = "376"
rpl_YOUREOPER :: ByteString
rpl_YOUREOPER = "381"
rpl_REHASHING :: ByteString
rpl_REHASHING = "382"
rpl_TIME :: ByteString
rpl_TIME = "391"
rpl_USERSSTART :: ByteString
rpl_USERSSTART = "392"
rpl_USERS :: ByteString
rpl_USERS = "393"
rpl_ENDOFUSERS :: ByteString
rpl_ENDOFUSERS = "394"
rpl_NOUSERS :: ByteString
rpl_NOUSERS = "395"
rpl_TRACELINK :: ByteString
rpl_TRACELINK = "200"
rpl_TRACECONNECTING :: ByteString
rpl_TRACECONNECTING = "201"
rpl_TRACEHANDSHAKE :: ByteString
rpl_TRACEHANDSHAKE = "202"
rpl_TRACEUNKNOWN :: ByteString
rpl_TRACEUNKNOWN = "203"
rpl_TRACEOPERATOR :: ByteString
rpl_TRACEOPERATOR = "204"
rpl_TRACEUSER :: ByteString
rpl_TRACEUSER = "205"
rpl_TRACESERVER :: ByteString
rpl_TRACESERVER = "206"
rpl_TRACENEWTYPE :: ByteString
rpl_TRACENEWTYPE = "208"
rpl_TRACELOG :: ByteString
rpl_TRACELOG = "261"
rpl_STATSLINKINFO :: ByteString
rpl_STATSLINKINFO = "211"
rpl_STATSCOMMANDS :: ByteString
rpl_STATSCOMMANDS = "212"
rpl_STATSCLINE :: ByteString
rpl_STATSCLINE = "213"
rpl_STATSNLINE :: ByteString
rpl_STATSNLINE = "214"
rpl_STATSILINE :: ByteString
rpl_STATSILINE = "215"
rpl_STATSKLINE :: ByteString
rpl_STATSKLINE = "216"
rpl_STATSYLINE :: ByteString
rpl_STATSYLINE = "218"
rpl_ENDOFSTATS :: ByteString
rpl_ENDOFSTATS = "219"
rpl_STATSLLINE :: ByteString
rpl_STATSLLINE = "241"
rpl_STATSUPTIME :: ByteString
rpl_STATSUPTIME = "242"
rpl_STATSOLINE :: ByteString
rpl_STATSOLINE = "243"
rpl_STATSHLINE :: ByteString
rpl_STATSHLINE = "244"
rpl_UMODEIS :: ByteString
rpl_UMODEIS = "221"
rpl_LUSERCLIENT :: ByteString
rpl_LUSERCLIENT = "251"
rpl_LUSEROP :: ByteString
rpl_LUSEROP = "252"
rpl_LUSERUNKNOWN :: ByteString
rpl_LUSERUNKNOWN = "253"
rpl_LUSERCHANNELS :: ByteString
rpl_LUSERCHANNELS = "254"
rpl_LUSERME :: ByteString
rpl_LUSERME = "255"
rpl_ADMINME :: ByteString
rpl_ADMINME = "256"
rpl_ADMINLOC1 :: ByteString
rpl_ADMINLOC1 = "257"
rpl_ADMINLOC2 :: ByteString
rpl_ADMINLOC2 = "258"
rpl_ADMINEMAIL :: ByteString
rpl_ADMINEMAIL = "259"
